### ISSUE TITLE
The detailed Scripts for training three main tasks: predcls, sgcls and sgdet.

### ISSUE THREAD

**Issue by ihaeyong** [SHTUPLUS/PySGG#1]
https://github.com/SHTUPLUS/PySGG/blob/c30a6a109a0257f51a94747ca84abdebe1911492/scripts/rel_train_BGNN_vg.sh#L9

According to https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch, 
For Predicate Classification (PredCls), we need to set:
MODEL.ROI_RELATION_HEAD.USE_GT_BOX True MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True

However, occurs an error at  https://github.com/SHTUPLUS/PySGG/blob/c30a6a109a0257f51a94747ca84abdebe1911492/pysgg/modeling/roi_heads/relation_head/model_bgnn.py#L813

Could you provide the exact scripts for predcls and sgcls modes?

**Comment by Scarecrow0** [comment]
Hi
I have added the patch for those two sub-tasks. 
The detailed script for running is here. https://github.com/SHTUPLUS/PySGG/blob/main/scripts/rel_train_BGNN_vg_predcls.sh
