### ISSUE TITLE
The question about message propagation

### ISSUE THREAD

**Issue by rlqja1107** [SHTUPLUS/PySGG#2]
<img width='300' src = 'https://user-images.githubusercontent.com/55014424/129822240-29e2dcb1-7559-4a60-99ae-482a9abab23a.png'>   
  
Above picture describes the message propagation method in GCN(Graph Convolution Network). In this method, when the information of the neighborhood is aggregated, it adds the message itself, then makes a transformation and adopts the activation function.  

<img width = '300' src = https://user-images.githubusercontent.com/55014424/129822618-768b5ba6-80e1-4bf8-9a2a-6906594f5a00.png>  

However, the BGNN method shows that for updating the node representation, the l-th representation of node is added after the message of neighborhood is transformed and is adopted the activation function.   
I wonder why BGNN takes the latter method.

**Comment by Scarecrow0** [comment]
Hi!

Thanks for attending our paper.

Since there are many graph iterations in our forward time (N graph iteration in K stage refinement), which leads to a quite deep GNN. To this end, we introduce the skip-connection mechanism into our GNN design, as shown in our formula.
