### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by ChCh1999** [SHTUPLUS/PySGG#3]
How much time does it take for your model training?  Why it shows that it requires over 9 days for me even when I change the  SOLVER.MAX_ITER from 70000 to 50000?  Is there anything wrong with my experiment？ I'm training on 4 Nvidia V100 GPU.
![image](https://user-images.githubusercontent.com/34148951/130891842-928422be-f7c0-4867-bc7d-f441b915c7f0.png)
![image](https://user-images.githubusercontent.com/34148951/130891938-ea8cf82e-07b3-45b5-b455-a785e21c8ca6.png)
The training script is :
![image](https://user-images.githubusercontent.com/34148951/130892187-fd00cc13-9475-4429-9e8f-c8f339b08a22.png)
Thanks for your help.

**Comment by Scarecrow0** [comment]
Hi, 

It takes about 10 hours to obtain a considerable performance on VG datasets on my machine(4 Titan V or Titan XP).
![image](https://user-images.githubusercontent.com/26022232/131697575-d493a8a6-f4b0-4958-bf9b-f458a017d355.png)
It seems that the time cost of each iteration is extremely high.
You may need to check which procedure of code consume so much time. You can try to comment the `torch.autograd.set_detect_anomaly(True)` in line 58 of tools/relation_train_net.py. It may slow down backward in some versions of Pytorch.
