### ISSUE TITLE
bug: instance resampling happened in evaluation 

### ISSUE THREAD

**Issue by rafa-cxg** [SHTUPLUS/PySGG#9]
both image-level and instance-level resampling should't apply to evaluation process. I noticed that image-level resampling  is disabled by
 ` if cfg.MODEL.ROI_RELATION_HEAD.DATA_RESAMPLING and self.split == 'train'` in **_pysgg/data/datasets/visual_genome.py_**
however, instance level resampling is not filter by it.

  you should change it to:  (code in `get_groundtruth()`)
![image](https://user-images.githubusercontent.com/49938663/145679075-c6e44940-6636-487c-82e5-0a99f3042726.png)

**Comment by rafa-cxg** [comment]
@Scarecrow0

**Comment by Scarecrow0** [comment]
In validation or test mode, the member: repeat_dict of VGDataset is left as an initial value of None already (in line 124 of __init__), so we do not need to add a check in function get_groundtruth.
However, you can add this check for safety.
Anyway, the resampling is only applied in training phrases in our implementation.

**Comment by rafa-cxg** [comment]
thanks for your replying. However, during training process, if you choose using one of the sampling method, it would generate  repeat_dict.pkl in path. So, it would caused sampling in val process.(I have checked this, instance sampling is applied in val_dataset.)

**Comment by Scarecrow0** [comment]
The repeat_dict.pkl is generated only for the training set. 
It won't load  and can't be used in validation or test. the self.repeat_dict remains none during the initialization of VGDataset in test or validation mode.
Please show the details of your checking process.

**Comment by rafa-cxg** [comment]
I  think your explanation is right. Maybe it is caused by randomly choice annotation of vg dataset?
you can see, gt_rels has a lot of same same relation with same sub obj id
![image](https://user-images.githubusercontent.com/49938663/145684103-c55a3079-f73e-4369-9525-102280ce6108.png)

I can show you returned gt_triblet_box, coordinate is the same
![image](https://user-images.githubusercontent.com/49938663/145684241-b24a8cb9-5fdb-49cb-b75a-10f0fcadcde6.png)

**Comment by rafa-cxg** [comment]
by the way, i would like to ask why calculation of  mean recall and others are performed on every single image? Shouldn't  calculating topk is about on whole val dataset?
![image](https://user-images.githubusercontent.com/49938663/145685046-9637442e-8a86-46d1-96ec-35c94b14c155.png)
One of possable situation: What if relation predictions in one image is less than k?  That's  not good

**Comment by Scarecrow0** [comment]
- The Visual Genome Stanford spilt does have this bug of repeat relationship annotation. You can directly load the annotation and check this repeat. Most SGG implementations ignore this repeat in val/test time. For fair comparison, we keep it the same as with previous works in our implementation.
- In evaluation metrics of visual relationship detection, the top-k recall means we only take at most 100 relationship predictions for matching with the GT relationship for each image. To this end, the number of predictions that can be generated by a model has no relevance to evaluation and is only a hyper-parameter for model design.
For the evaluation protocol, please refer to the previous works that proposed the Visual Genome Stanford split. They have detailed descriptions and disscusions, and we identically follow the previous evalutation pipeline in this codebase.

**Comment by rafa-cxg** [comment]
HELLO, how you seen the first and second picture i  posted? It seems like there are some repeated triblet in val...

**Comment by Scarecrow0** [comment]
> * The dataset itself, the Visual Genome Stanford spilt does have this issue of repeated relationship annotation. You can directly load the annotation and check this repeat. Most SGG works keep this repeat in val/test time. For fair comparison with previous works, we also keep the repeat annotation in our implementation.
> * In evaluation metrics of visual relationship detection, the top-k recall means we only take at most 100 relationship predictions for matching with the GT relationship for each image. To this end, the number of predictions that can be generated by a model has no relevance to evaluation and is only a hyper-parameter for model design.
>   For the evaluation protocol, please refer to the previous works that proposed the Visual Genome Stanford split. They have detailed descriptions and disscusions, and we identically follow the previous evalutation pipeline in this codebase.

: )
Please read my reply carefully. I re-wrote it for more clarity.

**Comment by rafa-cxg** [comment]
Hi, i really appreciated your explanation! But i haven't find the code to  **_"keep this repeat in val/test time"_** . I don't know where is it?  Thanks!

**Comment by Scarecrow0** [comment]
The repeat is already in the annotation of the dataset. We leave it untouched in test time.
The duplicated relation filtering only works in training time, as shown in the function get_groundtruth:

https://github.com/SHTUPLUS/PySGG/blob/main/pysgg/data/datasets/visual_genome.py#L299-315

**Comment by rafa-cxg** [comment]
get it! Thanks your dedicated works again!
